version: '3.8'

services:
  backend:
    image: restaurantedocker:latest
    container_name: restaurante
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/restaurantedocker

  mongo:
    image: mongo:6.0
    container_name: mongodb_local
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
