name: Crear y subir imagen Docker
on: 
  workflow_dispatch

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construir imagen Docker
        run: docker build -t angelrxdriguez/ejemplo-actions:latest .

      - name: Subir imagen a Docker Hub
        run: docker push angelrxdriguez/ejemplo-actions:latest

